#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const solverName = process.argv[2] || 'my-intent-solver';
const targetDir = path.join(process.cwd(), solverName);

if (fs.existsSync(targetDir)) {
    console.log(`⚠️  Directory ${solverName} already exists.`);
    process.exit(1);
}

console.log(`🛠️  Creating INTP solver: ${solverName}...`);
fs.mkdirSync(targetDir, { recursive: true });
fs.mkdirSync(path.join(targetDir, 'api'));

// Write api/index.py
fs.writeFileSync(path.join(targetDir, 'api', 'index.py'), `from flask import Flask, request, jsonify
import requests

app = Flask(__name__)

API_KEY = "YOUR_API_KEY"
PROVIDER_URL = "YOUR_PROVIDER_URL"

@app.route('/a2a', methods=['POST'])
def handle_intent():
    data = request.get_json()
    intent = data.get('intent', {})
    intent_id = data.get('intent_id')
    action = intent.get('action', '')
    target = intent.get('target', '')
    params = intent.get('params', {})

    # TODO: Add your fulfillment logic here
    # 1. Call your service API
    # 2. Extract the price and details
    # 3. Return the result

    return jsonify({
        "status": "fulfilled",
        "value": 0,
        "currency": "USD",
        "provider": "${solverName}",
        "details": f"Fulfilled {action}.{target} with params {params}"
    })

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8080)
`);

// Write requirements.txt
fs.writeFileSync(path.join(targetDir, 'requirements.txt'), 'flask\nrequests\n');

// Write vercel.json
fs.writeFileSync(path.join(targetDir, 'vercel.json'), JSON.stringify({
    rewrites: [{ source: '/a2a', destination: '/api/index' }]
}, null, 2));

// Write README
fs.writeFileSync(path.join(targetDir, 'README.md'), `# ${solverName}

An INTP solver generated by \`create-intent-solver\`.

## Quick Start

1. Add your API key and provider URL in \`api/index.py\`
2. Deploy to Vercel:
   \`\`\`bash
   vercel --prod
   \`\`\`
3. Register on INTP:
   \`\`\`bash
   cast send --rpc-url $RPC_URL --private-key $PK $CONTRACT "register(string,string[])" "https://your-url.vercel.app/a2a" '["YOUR_CAPABILITIES"]'
   \`\`\`

## Documentation

See the full INTP documentation at [github.com/Hormuz-Ai/intent-protocol](https://github.com/Hormuz-Ai/intent-protocol).
`);

console.log(`✅ Solver created in ./${solverName}`);
console.log('📋 Next steps:');
console.log(`   cd ${solverName}`);
console.log('   # Edit api/index.py with your API key and logic');
console.log('   vercel --prod');
console.log('   # Register on INTP with the URL Vercel gives you');
